#生产配置

#common:
#  minio:
#    endpoint: http://127.0.0.1:9000/
spring:
  profiles: prod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: org.h2.Driver
    #    schema: classpath:db/schema-h2.sql
    #    data: classpath:db/data-h2.sql
    #    url: jdbc:h2:mem:test
    url: jdbc:mysql://localhost:3306/sale_system?characterEncoding=utf8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: chr
    password: bai282828
    # mybatis-plus日志
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      global-config:
        db-config:
          logic-delete-field: deleted  # 全局逻辑删除的实体字段名
          logic-delete-value: 1 # 逻辑已删除值(默认为 1)
          logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/smartfire?serverTimezone=Asia/Shanghai&userSSL=false
#    username: root
#    password: superroot
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    initialSize: 1
#    minIdle: 3
#    maxActive: 20
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    # 合并多个DruidDataSource的监控数据
#    #useGlobalDataSourceStat: true